# api call for listing all leads
####
GET http://127.0.0.1:8000/api/leads/
Accept: application/json
Authorization: Token c908d29f7a1720b07a9eb9a8e3263eb5b75dfd40

#Api call for creating lead
###
POST  http://127.0.0.1:8000/api/leads/
Content-Type: application/json


{
  "name":"techlab",
  "email":"techlab@gmail.com" ,
  "company":"techlab",
  "phone": 456789,
  "source":"website" ,
  "requirement":"mobile application development ",
  "budget":300000,
  "notes":"develop mobile application"
}


#Api call for retrieving a lead
###
GET http://127.0.0.1:8000/api/leads/1/
Accept: application/json

#API call for updating lead
###
PUT  http://127.0.0.1:8000/api/leads/2/
Content-Type: application/json


{
  "name":"techlab",
  "email":"techlab@gmail.com" ,
  "company":"techlab",
  "phone": 89898989,
  "source":"website" ,
  "requirement":"mobile application development ",
  "budget":350000,
  "notes":"develop mobile application"
}


#Api call for deleting  a lead
###
DELETE  http://127.0.0.1:8000/api/leads/1/
Accept: application/json


#api call for lead summary
###
GET  http://127.0.0.1:8000/api/leads/summary/
Accept: application/json


#api call for getting token
###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username":"admin",
  "password":"admin"
}

# localStorage 
